### ISSUE TITLE
FastCGI long Param error

### ISSUE THREAD

**Issue by mrebello** [soywiz-archive/csharputils#3]
I found an error in FastcgiPacketReader.cs in function ReadVariableInt.
The rotation of bit was to wrong direction and then 0xFF should by 0x7F (cut the eight bit).
I think that correct code is:

static public int ReadVariableInt(Stream Stream)
        {
            int Byte = Stream.ReadByte();
            if (Byte < 0) throw (new Exception("Can't ready more bytes"));
            if ((Byte & 0x80) != 0)
            {
                return (
                    (Byte & 0x7F    ) << 24 |
                    Stream.ReadByte() << 16 |
                    Stream.ReadByte() <<  8 |
                    Stream.ReadByte() 
                );
            }
            else
            {
                return Byte;
            }
        }

**Comment by soywiz** [comment]
Oh yeah. It seems you are right!
Thanks :) I'll fix it asap.
